// Generated by https://quicktype.io

export interface NasaData {
    collection: Collection;
}

export interface Collection {
    version:  string;
    href:     string;
    items:    Item[];
    metadata: Metadata;
    links:    CollectionLink[];
}

export interface Item {
    href:   string;
    data:   Datum[];
    links?: ItemLink[];
}

export interface Datum {
    description:        string;
    title:              string;
    nasa_id:            string;
    date_created:       string;
    keywords?:          string[];
    media_type:         MediaType;
    description_508?:   string;
    center:             string;
    photographer?:      string;
    location?:          string;
    secondary_creator?: string;
    album?:             string[];
}

export enum MediaType {
    Audio = "audio",
    Image = "image",
    Video = "video",
}

export interface ItemLink {
    href:    string;
    rel:     Rel;
    render?: MediaType;
}

export enum Rel {
    Captions = "captions",
    Preview = "preview",
}

export interface CollectionLink {
    rel:    string;
    prompt: string;
    href:   string;
}

export interface Metadata {
    total_hits: number;
}
